const PLAYLIST_URL="https://iptv-org.github.io/iptv/index.m3u";
const APP_VERSION="1.0";
const STORAGE={favs:"worldtv_favourites_v1",recent:"worldtv_recent_v1",cache:"worldtv_playlist_cache_v1",cacheTime:"worldtv_playlist_cache_time_v1"};
const COUNTRIES={US:"United States",GB:"United Kingdom",UK:"United Kingdom",ES:"Spain",FR:"France",DE:"Germany",IT:"Italy",PT:"Portugal",TR:"Turkey",AZ:"Azerbaijan",JP:"Japan",CN:"China",KR:"South Korea",IN:"India",BR:"Brazil",AR:"Argentina",MX:"Mexico",CA:"Canada",AU:"Australia",NL:"Netherlands",BE:"Belgium",CH:"Switzerland",AT:"Austria",SE:"Sweden",NO:"Norway",DK:"Denmark",FI:"Finland",PL:"Poland",RO:"Romania",BG:"Bulgaria",GR:"Greece",RU:"Russia",UA:"Ukraine",AE:"United Arab Emirates",SA:"Saudi Arabia",QA:"Qatar",IR:"Iran",IQ:"Iraq",IL:"Israel",EG:"Egypt",MA:"Morocco",ZA:"South Africa",NG:"Nigeria",INT:"International",XX:"International",UN:"International"};
const state={channels:[],filtered:[],countries:[],country:"All",group:"All",query:"",section:"browse",active:null,loading:true,error:"",hls:null};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const safeParse=(k,f)=>{try{let r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}};
const saveJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const channelId=c=>`${c.name}::${c.url}`;
function getFavs(){return new Set(safeParse(STORAGE.favs,[]))}function setFavs(s){saveJSON(STORAGE.favs,[...s])}
function getRecent(){return safeParse(STORAGE.recent,[])}function setRecent(a){saveJSON(STORAGE.recent,a.slice(0,30))}
function countryLabel(code){if(!code||code==="All")return"All countries";let up=String(code).toUpperCase();return COUNTRIES[up]||up}
function parseAttrs(line){let attrs={},re=/([\w-]+)="([^"]*)"/g,m;while((m=re.exec(line)))attrs[m[1]]=m[2];return attrs}
function inferCountry(attrs,name){let raw=[attrs["tvg-country"],attrs.country,attrs.countries,attrs["group-title"]].filter(Boolean).join(" ");let m=raw.match(/(?:^|[,;:\s])([A-Z]{2})(?:$|[,;:\s])/);if(m)return m[1];let low=norm(`${attrs["group-title"]||""} ${name||""}`);for(let [c,n] of Object.entries(COUNTRIES)){if(c.length===2&&low.includes(norm(n)))return c}return"INT"}
function parseM3U(text){let lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){let line=lines[i];if(!line.startsWith("#EXTINF"))continue;let attrs=parseAttrs(line),comma=line.indexOf(","),display=comma>=0?line.slice(comma+1).trim():"",url="";for(let j=i+1;j<Math.min(lines.length,i+6);j++){if(lines[j]&&!lines[j].startsWith("#")){url=lines[j];break}}if(!url||!/^https?:\/\//i.test(url))continue;let name=attrs["tvg-name"]||display||attrs["tvg-id"]||"Unknown channel",group=attrs["group-title"]||"General",logo=attrs["tvg-logo"]||"",country=inferCountry(attrs,name);out.push({name,group,logo,url,country,countryName:countryLabel(country),tvgId:attrs["tvg-id"]||"",lang:attrs["tvg-language"]||attrs.language||""})}return out.sort((a,b)=>a.countryName.localeCompare(b.countryName)||a.name.localeCompare(b.name))}
async function loadPlaylist(force=false){
  state.loading = true;
  state.error = "";
  renderShell();

  try{
    const r = await fetch(PLAYLIST_URL, { cache: force ? "reload" : "default" });
    if(!r.ok) throw new Error(`Playlist returned ${r.status}`);
    const text = await r.text();

    // v1.0.1 fix:
    // Do NOT save the full IPTV-org M3U playlist into localStorage.
    // The playlist is huge and exceeds browser storage quotas on many devices.
    state.channels = parseM3U(text);
    hydrateCountries();
    state.loading = false;
    applyFilters();
    render();
  }catch(err){
    state.loading = false;
    state.error = `Could not load playlist. This can happen if GitHub Pages, your browser, or the network blocks the M3U request. Try refreshing, disabling content blockers for this page, or opening it on Chrome. Details: ${err.message || err}`;
    render();
  }
}

function hydrateCountries(){let m=new Map();for(let c of state.channels)m.set(c.country,{code:c.country,name:countryLabel(c.country),count:(m.get(c.country)?.count||0)+1});state.countries=[...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function currentGroups(){let arr=state.channels.filter(c=>state.country==="All"||c.country===state.country);return["All",...new Set(arr.map(c=>c.group||"General"))].sort((a,b)=>a.localeCompare(b))}
function applyFilters(){let q=norm(state.query);state.filtered=state.channels.filter(c=>(state.country==="All"||c.country===state.country)&&(state.group==="All"||c.group===state.group)&&(!q||norm([c.name,c.group,c.countryName,c.lang,c.tvgId].join(" ")).includes(q)))}
function addRecent(c){let rec=getRecent().filter(x=>x.id!==channelId(c));rec.unshift({id:channelId(c),name:c.name,country:c.country,countryName:c.countryName,group:c.group,logo:c.logo,url:c.url,at:new Date().toISOString()});setRecent(rec)}
function toggleFav(c){let f=getFavs(),k=channelId(c);f.has(k)?f.delete(k):f.add(k);setFavs(f);render()}
function playChannel(c){state.active=c;addRecent(c);renderPlayer();setTimeout(()=>attachPlayer(c),50)}
function attachPlayer(c){let v=$("#videoPlayer");if(!v)return;if(state.hls){try{state.hls.destroy()}catch{}state.hls=null}v.removeAttribute("src");v.load();let src=c.url,isHls=/\.m3u8($|\?)/i.test(src)||src.includes(".m3u8");if(isHls&&window.Hls&&Hls.isSupported()){let h=new Hls({lowLatencyMode:true,backBufferLength:60,maxBufferLength:30});state.hls=h;h.loadSource(src);h.attachMedia(v);h.on(Hls.Events.ERROR,(_,d)=>{if(d?.fatal)showMsg("This stream failed in the browser. Try another channel or open stream.",true)})}else{v.src=src}v.play().catch(()=>showMsg("Press play to start. Some browsers block autoplay.",false))}
function showMsg(msg,err=false){let b=$("#playerMessage");if(b){b.textContent=msg;b.classList.toggle("error",err);b.hidden=false}}
function renderPlayer(){let c=state.active,p=$("#playerPanel");if(!p)return;let fav=c&&getFavs().has(channelId(c));p.innerHTML=c?`<div class="player-header"><div class="channel-identity"><div class="logo-box">${c.logo?`<img src="${esc(c.logo)}" alt="" onerror="this.remove()">`:`<span>${esc((c.name||"?").slice(0,1))}</span>`}</div><div><div class="eyebrow">${esc(c.countryName)} · ${esc(c.group||"General")}</div><h2>${esc(c.name)}</h2></div></div><div class="player-actions"><button class="pill-btn ${fav?"active":""}" data-action="fav-active">${fav?"Saved ★":"Save ★"}</button><a class="pill-btn" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Open stream</a></div></div><div class="video-wrap"><video id="videoPlayer" controls playsinline></video><div id="playerMessage" class="player-message" hidden></div></div><p class="small-note">Streams come from the public IPTV-org playlist. Availability varies by provider, browser and country.</p>`:`<div class="empty-player"><h2>Choose a channel</h2><p>Select a country, pick a channel, and it will play here.</p></div>`}
function renderShell(){document.body.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand" data-nav="browse"><div class="logo-mark">TV</div><div><strong>WorldTV</strong><span>Country IPTV Player</span></div></div><nav class="nav"><button class="nav-btn ${state.section==="browse"?"active":""}" data-nav="browse">Browse</button><button class="nav-btn ${state.section==="favourites"?"active":""}" data-nav="favourites">Favourites</button><button class="nav-btn ${state.section==="recent"?"active":""}" data-nav="recent">Recent</button><button class="nav-btn ${state.section==="about"?"active":""}" data-nav="about">About</button></nav></header><main><section id="playerPanel" class="player-panel"></section><section id="contentPanel"></section></main></div>`;renderPlayer();if(state.loading)$("#contentPanel").innerHTML=`<section class="loading-card"><div class="loader"></div><h1>Loading world channels…</h1><p>Fetching and parsing the IPTV-org playlist.</p></section>`}
function controls(){return`<section class="controls-card"><div class="controls-grid"><label><span>Country</span><select id="countrySelect"><option value="All">All countries (${state.channels.length})</option>${state.countries.map(c=>`<option value="${esc(c.code)}" ${state.country===c.code?"selected":""}>${esc(c.name)} (${c.count})</option>`).join("")}</select></label><label><span>Category</span><select id="groupSelect">${currentGroups().map(g=>`<option value="${esc(g)}" ${state.group===g?"selected":""}>${esc(g)}</option>`).join("")}</select></label><label><span>Search</span><input id="searchBox" type="search" placeholder="Search channel, category, country..." value="${esc(state.query)}"></label><button id="clearFilters" class="pill-btn">Clear</button></div>${state.error?`<div class="warning">${esc(state.error)}</div>`:""}</section>`}
function card(c){let fav=getFavs().has(channelId(c));return`<article class="channel-card"><button class="channel-main" data-action="play" data-id="${esc(channelId(c))}"><div class="logo-box">${c.logo?`<img src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.remove()">`:`<span>${esc((c.name||"?").slice(0,1))}</span>`}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.countryName)} · ${esc(c.group||"General")}</p></div></button><button class="fav-btn ${fav?"active":""}" data-action="fav" data-id="${esc(channelId(c))}">★</button></article>`}
function renderBrowse(){applyFilters();$("#contentPanel").innerHTML=`<section class="hero"><div><div class="eyebrow">WorldTV v${APP_VERSION}</div><h1>Choose a country. Watch live TV.</h1><p>A cleaner front-end for the public IPTV-org playlist. Built for browsing, quick playback and fewer ugly IPTV-list headaches.</p></div><button class="pill-btn" id="refreshPlaylist">Refresh playlist</button></section>${controls()}<section class="result-head"><h2>${state.filtered.length} channels</h2><p>${state.country==="All"?"All countries":esc(countryLabel(state.country))}${state.group==="All"?"":" · "+esc(state.group)}</p></section><section class="channel-grid">${state.filtered.map(card).join("")||`<div class="empty-card">No channels found.</div>`}</section>`}
function renderFavourites(){let f=getFavs(),arr=state.channels.filter(c=>f.has(channelId(c)));$("#contentPanel").innerHTML=`<section class="page-head"><div><h1>Favourites</h1><p>${arr.length} saved channel${arr.length===1?"":"s"}.</p></div></section><section class="channel-grid">${arr.map(card).join("")||`<div class="empty-card">No favourites yet.</div>`}</section>`}
function renderRecent(){let arr=getRecent().map(r=>state.channels.find(c=>channelId(c)===r.id)||r).filter(Boolean);$("#contentPanel").innerHTML=`<section class="page-head"><div><h1>Recent</h1><p>Your last watched channels on this device.</p></div></section><section class="channel-grid">${arr.map(card).join("")||`<div class="empty-card">No recent channels yet.</div>`}</section>`}
function renderAbout(){$("#contentPanel").innerHTML=`<section class="about-card"><h1>About WorldTV</h1><p>WorldTV is a clean browser player for the public IPTV-org M3U playlist. It does not host channels and does not control stream availability. v1.0.1 avoids storing the huge playlist in browser storage.</p><div class="stat-grid"><div><strong>${state.channels.length}</strong><span>channels loaded</span></div><div><strong>${state.countries.length}</strong><span>countries / regions</span></div><div><strong>${getFavs().size}</strong><span>favourites</span></div></div><div class="notes"><p><strong>Why some channels fail:</strong> streams can be offline, geo-blocked, browser-incompatible, overloaded, or changed by the provider.</p><p><strong>Playback:</strong> HLS streams use HLS.js where the browser needs it. Safari usually supports HLS natively.</p><p><strong>Source:</strong> ${esc(PLAYLIST_URL)}</p></div></section>`}
function render(){if(!$(".app-shell"))renderShell();renderPlayer();$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.nav===state.section));if(state.loading)return;if(state.section==="browse")renderBrowse();if(state.section==="favourites")renderFavourites();if(state.section==="recent")renderRecent();if(state.section==="about")renderAbout()}
function findById(k){return state.channels.find(c=>channelId(c)===k)}
function handleClick(e){let nav=e.target.closest("[data-nav]");if(nav){state.section=nav.dataset.nav;render();return}let a=e.target.closest("[data-action]");if(a){let c=findById(a.dataset.id);if(a.dataset.action==="play"&&c)playChannel(c);if(a.dataset.action==="fav"&&c)toggleFav(c);if(a.dataset.action==="fav-active"&&state.active)toggleFav(state.active);return}if(e.target.id==="clearFilters"){state.country="All";state.group="All";state.query="";applyFilters();render()}if(e.target.id==="refreshPlaylist"){localStorage.removeItem(STORAGE.cache);localStorage.removeItem(STORAGE.cacheTime);loadPlaylist(true)}}
function handleInput(e){if(e.target.id==="searchBox"){state.query=e.target.value||"";applyFilters();renderBrowse()}}
function handleChange(e){if(e.target.id==="countrySelect"){state.country=e.target.value||"All";state.group="All";applyFilters();renderBrowse()}if(e.target.id==="groupSelect"){state.group=e.target.value||"All";applyFilters();renderBrowse()}}
function boot(){renderShell();document.addEventListener("click",handleClick);document.addEventListener("input",handleInput);document.addEventListener("change",handleChange);if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{});loadPlaylist()}
document.addEventListener("DOMContentLoaded",boot);
